console.log("Apple Inc.")
console.log("One Apple Park Way")
console.log("Cupertino, CA")
console.log("95014")
console.log("+1 408-996-1010")
console.log()
console.log()
console.log("Apple Inc.\nOne Apple Park Way\nCupertino, CA\n95014\n+1 408-996-1010")
console.log()
console.log()
console.log("x\to\tx\no\tx\to\nx\to\tx")
